### POST /signup
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
	"first_name": "John",
  	"email": "john2@gmail.com",
  	"password": "John1234!",
  	"confirm_password": "John1234!"
}

### POST /login
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John1234!"
}

### POST /signout
POST http://localhost:8080/signout HTTP/1.1




### GET /me
GET http://localhost:8080/me HTTP/1.1

### PATCH /me/updatepassword
PATCH http://localhost:8080/me/update-password HTTP/1.1
Content-Type: application/json

{
  	"password": "John1234!",
  	"confirm_password": "John1234!",
  	"new_password": "BlaBla123!"
}